version: '3'

services:
  api:
    build: ./simple_api

    volumes:
      - ./simple_api:/data

    ports:
      - 5000:5000

  website:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html

    depends_on:
      - api

    ports:
      - 8081:80

